#!/usr/bin/sh

INSTALL_PATH="/usr/local/bin"

if [ -L "${INSTALL_PATH}/url_obfuscator" ]; then
	rm "${INSTALL_PATH}/url_obfuscator"
fi

ln -sv $(realpath url_obfuscator.py)  "${INSTALL_PATH}/url_obfuscator"

if [ -f "${INSTALL_PATH}/url_obfuscator" ]; then
	chmod -v 755 "${INSTALL_PATH}/url_obfuscator"
fi
